# store all the configurations here

##### FOR THE CLASS RestructureFileDirectoryJtubespeech #####

# the folder where the raw vtt and wav16k folder resides
root_folder: './datasets/jtubespeech/jtubespeech_data_small/id'

# the directory name created to store the restructured data for the preprocessing task
dest_folder_name: 'annotated_data'

# file type of the folder name needed to extract the raw audio and transcript
file_type_vtt: 'vtt'
file_type_wav: 'wav16k'


##### FOR THE CLASS UtilsJtubespeech #####

# main data folder with all the raw data that is to be processed
main_data_folder: 'datasets/jtubespeech/jtubespeech_data_small/id/annotated_data'

# new directory name for the preprocessed data
preprocessed_data_folder: 'datasets/jtubespeech/jtubespeech_data_small/id/annotated_data_preprocessed_wav'

# the audio format of the exported preprocessed audio
audio_format: 'wav'